### ISSUE TITLE
Cannot sign out of application (BUG-000085806)

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#151]
When clicking 'sign out' the app refreshes and signs back in again. Signing out should return the gallery to showing public content only.

**Comment by allisonmuise** [comment]
in devtopia
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/711#issuecomment-184448

**Comment by CTLocalGovTeam** [comment]
@allisonmuise As discussed during the call last week, we decided to fall back for displaying a white sign in page like it is implemented in crowdsource manager app. However we were able to sign out the user without automatically signing in. Once user signs out, public content from the group is displayed instead of sign in page. 
We will provide this fix in the next release.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,
While fixing this issue, we have observed that in a particular scenario, the application behaves differently in hosted environment and when deployed on an external server.

This scenario is only applicable when the published app is private (not shared or shared only with Org) and template is hosted on external webserver. The same scenario works as expected with AGOL hosted environment.

**External server:**

1. On initial load, identity manager is displayed 
2. On providing valid credentials, user is signed into the application and private as well as public contents are displayed correctly.
3. When user signs out of the application, identity manager is displayed. This is expected because the app is private and it cannot reuse credentials from cache/cookies as template is externally hosted. 
4. User goes on to provide valid credentials, 
  * You would expect that user is signed in and able to see all contents.    
  * However, the observed behavior is that only public items are displayed with a ‘Sign-in’ button.
  * This is because, the app is private and identity manager is actually asking credentials to access the app. Once the app is loaded, it does not attempt to use the credentials automatically.
  * We cannot have the app reuse the credentials automatically because this will again lead to app not being able to sign out, i.e. it will automatically keep on signing you in, even after you click sign out. 
5. User has to click 'Sign in' button again, then user is automatically signed in and public as well as private contents are displayed.

**Hosted environment:**

1. On initial load, AGOL Sign in page is displayed
2. On providing valid credentials, user is signed into the application and private as well as public contents are displayed correctly.
3. When user signs out of the application, public contents are displayed and Sign in button is displayed on top right corner correctly.
4. User has to click 'Sign in' button, then user is automatically signed in and public as well as private contents are displayed correctly.

In hosted environment, AGOL sign in page is **not** displayed in step 3 because the credentials are fetched from cache, so user is automatically signed in to the application.

In other scenarios i.e., when application is public, both external as well as AGOL hosted template, behave the same way as expected.

Please let us know your inputs on this.

**Comment by allisonmuise** [comment]
verified
