### ISSUE TITLE
proxy set up issues

### ISSUE THREAD

**Issue by chen7012** [Esri/map-and-app-gallery-template#163]
this template comes with the proxy folder, but doesn't have enough documentations talking about how to set it up, and also the proxy doesn't work well with this template. In addition, when the proxy set up, some thumbnails are missing. 

So please follow the steps below to set up the proxy:

1. inside the config.js file, set the "proxyUrl" to the "http://your path to the app/proxy/proxy.ashx?", also make sure the "portalURL" is pointing to "http://www.arcgis.com/" instead of your organization domain

2. inside the proxy.config file:
\<serverUrl url="http://www.arcgis.com/"  matchAll="true" username ="test" password ="test"/>

3. Since there is an existing bug related, so the proxy will send some invalid requests.  <BUG-000088254 The JavaScript Identity Manager requests are incorrectly formatted, causing errors when going through the proxy.>
So we need to make changes in the code to workaround this bug inside proxy.ashx file by adding the following code: 
 if ((uri.Split('?').Length - 1) > 1) 
 { 
 StringBuilder sb = new StringBuilder(uri); 
 sb[uri.LastIndexOf("?")] = '&'; 
 uri = sb.ToString(); 
 } 
...after this line: 
 if (uri.StartsWith("http%3a%2f%2f", StringComparison.InvariantCultureIgnoreCase) || uri.StartsWith("https%3a%2f%2f", StringComparison.InvariantCultureIgnoreCase)) 
The following namespace also needs to be added: 
using System.Text; 

4. Since If you are storing login information (username and password or client_id and client_secret) in the proxy you will want to use the addProxyRule option so that requests to the resources with the specified URL prefix are routed through the proxy. But the template is actually not using addProxyRule to append proxy prefix, so  you will need to make changes inside the coreLibrary\bootStrapper.js file by commenting the lines:
// esriConfig.defaults.io.proxyUrl = dojoConfig.baseURL + dojo.configData.values.proxyUrl;
 // esriConfig.defaults.io.alwaysUseProxy = false;
 // esriConfig.defaults.io.timeout = 180000;
instead adding the code :
urlUtils.addProxyRule({
                    urlPrefix: "http://www.arcgis.com/sharing/rest",
                    proxyUrl: dojo.configData.values.proxyUrl
 });
5. Then the application should work, which means you could see the full list of the items inside the group without signing in. But you will find some thumbnails are missing, so you will need to do extra steps to make the thumbnails show up, which is inside the widgets/gallery/gallery.js file after line 249:
<br/>change from: <br/>
domStyle.set(divThumbnailImage, "background", 'url(' + itemResult.thumbnailUrl + ') no-repeat center center'); 
<br/>To: <br/>
var thumbnailUrl_proxy = dojo.configData.values.proxyUrl + itemResult.thumbnailUrl; 
domStyle.set(divThumbnailImage, "background", 'url(' + thumbnailUrl_proxy + ') no-repeat center center'); 

PS: there is still a problem with this is when you trying to open an web map application, it will launch a new tab in browser and require you to sign in again. But you could access web app directly.

**Comment by allisonmuise** [comment]
Thanks for bringing this to our attention @chen7012 . This app is also available as a hosted web app template in both ArcGIS Portal and ArcGIS Online. Configuring a proxy is not required to use the app in either of these environments.

**Comment by wspiking** [comment]
Hi @chen7012.  Thank you for taking the time to share your proxy fix.....I've been banging my head trying to get this to work.

I'm having troubles following Step 3.  Can you share this snippet of code from your proxy.ashx?

Where exactly are you adding the following code?  Anywhere in the proxy.ashx?

if ((uri.Split('?').Length - 1) > 1) 
{ 
StringBuilder sb = new StringBuilder(uri); 
sb[uri.LastIndexOf("?")] = '&'; 
uri = sb.ToString(); 
} 

And then add then following code?

if (uri.StartsWith("http%3a%2f%2f", StringComparison.InvariantCultureIgnoreCase) || uri.StartsWith("https%3a%2f%2f", StringComparison.InvariantCultureIgnoreCase)) 

Any help would be appreciated.

Thank you,

Bill

**Comment by allisonmuise** [comment]
@MikeTschudi : Please assess

**Comment by MikeTschudi** [comment]
Branch proxy-update commit a3827b2cb09cd428727de0045f1b822edb1f91b7 is based on the changes that @chen7012 figured out.

The existing bug referred to appears when the JSAPI's Portal is used with a proxy; a bug report has been filed for it. In the meantime, proxy.ashx was modified to work around this bug. @wspiking, @chen7012 is referencing a newer version of the proxy, which is why you're not finding the "StringComparison.InvariantCultureIgnoreCase" landmark. I made the modifications to the repository's version of the proxy and will explore updating the proxy to the current 1.1 version in subsequent commit(s) in this branch, so please use the above commit URL to get just these changes.

For using the proxy, there's now a pair of sample tags in the proxy.config file--one for username and password and one for clientId and clientSecret. Pick one method, add the credentials, and uncomment that tag.

Another change is that the path to the proxy program is optional. If config.js' proxyUrl value is an empty string, then the proxy is not set up. It will work for public content and provide a message if the group has no public content. If the path is provided, on the other hand, it will be used by the app to access config.js' portalURL both for the group account and for the thumbnails. Note that the proxyUrl path in the Nov_2015 release was incorrect: the leading forward slash should not be there by default.

@allisonmuise, please review changes and instructions for clarity

**Comment by allisonmuise** [comment]
@MikeTschudi : please merge this change into the develop branch.

**Comment by MikeTschudi** [comment]
Merged via commit 1168552846af7e4b21460448b2a25e0adf2829de
