### ISSUE TITLE
Add summary text to grid view

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#176]
Hi,
St. Louis County, MO will be replacing their embedded gallery with the gallery app because they have many items in their gallery and like the search functionality available in the app. On their wish list for future versions of the app is to make the item description visible when the items are being viewed in grid view. They suggested putting the description where the items currently show the item type, such as “Web Mapping Application” in gray. When the description does not fit, an ellipsis could be used and a tool tip could show the entire description. Another option would be to change the thumbnail into a description in the same way that an embedded gallery does.
Thanks for considering making this enhancement in the future.
Jennifer

Jennifer Kuntz, GISP

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Here is a mockup showing summary text in grid view. We added another line below the item type.
Please let us know what you think.

![image](https://cloud.githubusercontent.com/assets/2959186/12446048/db2f4c1a-bf8d-11e5-9c30-fb1d10788b7b.png)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : This looks good. Does the full summary show when hovering the cursor over the snippet?

How does this look in the mobile form factor?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise The grid view is not supported in mobile form factor due to limited real estate (especially in portrait orientation). It is only available in desktop and tablet browsers.

If we want to also display the full summary when hovering the cursor, then we can adopt either of the two following approaches. The hover action is supported only on desktop browsers and wont be supported in tablet and mobile browsers.

#### Show the summary in a separate popup like this
![image](https://cloud.githubusercontent.com/assets/2959186/12482137/ffb578c0-c073-11e5-8cfe-66690df6f67a.png)

--------


#### Show the summary as an overlay
![image](https://cloud.githubusercontent.com/assets/2959186/12482168/2c0d602c-c074-11e5-9aa5-55a9b288efc8.png)

**Comment by allisonmuise** [comment]
When the summary text is too long to fit into the thumbnail space, it gets cut off. Text that is too long should end in an ellipsis - the same as the Public Gallery.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

In Public Gallery app, character length of summary text is limited to 120. If summary text contains more than 120 characters then ellipsis(...) is getting added. 
 
In given screenshot, summary text with ellipsis is shown-

![screen shot 2016-03-23 at 8 23 35 pm](https://cloud.githubusercontent.com/assets/2959186/13989174/2f3f4cbe-f135-11e5-8af8-5e3fbab3d8cd.png)

Should we follow the same approach? Please confirm.

**Comment by allisonmuise** [comment]
Yes, please follow the same approach.

**Comment by allisonmuise** [comment]
verified
