### ISSUE TITLE
Add support for vector basemap group

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#217]
Add support for
Here is an org configured with the vector basemap gallery: http://devtesting.mapsdevext.arcgis.com

If the org is configured with useVectorBasemaps: true, then the vector basemap group query should be used as the basemap gallery.

Here’s what the self call looks like:
![image](https://cloud.githubusercontent.com/assets/2752195/24810966/113d96c0-1b79-11e7-849e-dfa2afcd18a7.png)

**Comment by allisonmuise** [comment]
@MikeTschudi Could you take a look at this?

**Comment by MikeTschudi** [comment]
@allisonmuise, nominally, this is straightforward, but the app has assumptions and redundancies that complicate the task and its verification. It may take most of a week to implement.

**Comment by allisonmuise** [comment]
@MikeTschudi Thanks for looking into this. Please don't do any further work on this for now. It may go to CT.

**Comment by MikeTschudi** [comment]
@allisonmuise, @CTLocalGovTeam, Mike M provided a clear path for adjusting the group: https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/pull/1580/files:

In `searchAGOLGroupItems.js`, after
```
dojo.BaseMapGroupQuery = this._portal.basemapGalleryGroupQuery;
```
add
```                                   
if (this._portal.hasOwnProperty("useVectorBasemaps") && this._portal.useVectorBasemaps === true && 
  this._portal.vectorBasemapGalleryGroupQuery) {
  dojo.BaseMapGroupQuery = this._portal.vectorBasemapGalleryGroupQuery;
}                     
```                                                                             
and after
```
dojo.BaseMapGroupQuery = data.results[0].portal.basemapGalleryGroupQuery;
```
add
```
if (data.results[0].portal.hasOwnProperty("useVectorBasemaps") &&
  data.results[0].portal.useVectorBasemaps === true &&
  data.results[0].portal.vectorBasemapGalleryGroupQuery) {
  dojo.BaseMapGroupQuery = data.results[0].portal.vectorBasemapGalleryGroupQuery;
}                                                                                
```

Aside from this, however, the custom basemap switcher is not cycling correctly: with the first click on the widget, the thumbnail changes but the map's basemap does not change. After this, the switcher no longer has an attached click event. Rather than pursuing that fix, Mike suggests replacing the custom widget with one more standard. For example, in [information-lookup](https://github.com/Esri/information-lookup), he has isolated the basemap switcher setup and the pieces can be re-used in map-and-app-gallery-template.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Please assess the LOE required to fix the MAG basemap widget as outlined above by @MikeTschudi 

Once the LOE estimate is complete, please let @ScottOppmann and I know so that we can determine if this is something we can fit in for 5.2

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I know you can't access the org referenced in the first comment. I am working on a solution.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : You should be able to view this new setting in any devext organization.

**Comment by allisonmuise** [comment]
verified on devext
